In [2]:
import pandas as pd

db_uri = "sqlite:////Users/eidens/Projects/mecadoi-archives/batch/batch.sqlite3"

query = """
SELECT *
FROM deposition_attempt
WHERE deposition LIKE '%https://orcid.org/http://orcid.org%'
"""

df = pd.read_sql_query(query, db_uri)
df

,id_parsed_file,deposition,attempted_at,succeeded,id,verification_failed,status
0,1053,"<doi_batch xmlns=""http://www.crossref.org/sche...",2024-09-04 05:23:01.723704,None,8770,None,1
1,1173,"<doi_batch xmlns=""http://www.crossref.org/sche...",2025-01-05 05:23:02.471156,None,10454,None,20
2,1173,"<doi_batch xmlns=""http://www.crossref.org/sche...",2025-01-06 02:23:32.963375,None,10561,None,20
3,1173,"<doi_batch xmlns=""http://www.crossref.org/sche...",2025-01-13 02:23:31.672141,None,10672,None,20
4,1173,"<doi_batch xmlns=""http://www.crossref.org/sche...",2025-01-20 02:23:32.376670,None,10785,None,20
5,1173,"<doi_batch xmlns=""http://www.crossref.org/sche...",2025-01-27 02:23:36.467056,None,10903,None,20
6,1173,"<doi_batch xmlns=""http://www.crossref.org/sche...",2025-02-03 02:23:29.000194,None,11027,None,20
7,1173,"<doi_batch xmlns=""http://www.crossref.org/sche...",2025-02-10 02:23:29.733790,None,11158,None,20
8,1173,"<doi_batch xmlns=""http://www.crossref.org/sche...",2025-02-17 02:23:29.832774,None,11294,None,20
9,1173,"<doi_batch xmlns=""http://www.crossref.org/sche...",2025-02-24 02:23:29.802292,None,11434,None,1
10,1515,"<doi_batch xmlns=""http://www.crossref.org/sche...",2025-11-19 05:23:01.913146,None,29088,None,1

In [5]:
to_fix = df.iloc[9:]
to_fix

,id_parsed_file,deposition,attempted_at,succeeded,id,verification_failed,status
9,1173,"<doi_batch xmlns=""http://www.crossref.org/sche...",2025-02-24 02:23:29.802292,None,11434,None,1
10,1515,"<doi_batch xmlns=""http://www.crossref.org/sche...",2025-11-19 05:23:01.913146,None,29088,None,1

In [20]:
from difflib import unified_diff

original_depositions = to_fix['deposition'].tolist()
corrected_depositions = [
    deposition.replace('https://orcid.org/http://orcid.org', 'https://orcid.org')
    for deposition in original_depositions
]
for i, (original, fixed) in enumerate(zip(original_depositions, corrected_depositions)):

    print(f'Deposition {i}:')

    dois_affected = [line for line in original.splitlines() if "<doi>" in line.lower()]
    for line in dois_affected:
        print(line)

    diff = unified_diff(original.splitlines(), fixed.splitlines())
    print('\n'.join(diff))

    print()

Deposition 0:
        <doi>10.15252/rc.2025414611</doi>
        <doi>10.15252/rc.2025737807</doi>
        <doi>10.15252/rc.2025897098</doi>
---

+++

@@ -142,7 +142,7 @@

               <institution_department>Department of Genetics, Faculty of Biology</institution_department>
             </institution>
           </affiliations>
-          <ORCID authenticated="true">https://orcid.org/http://orcid.org/0000-0002-5512-0443</ORCID>
+          <ORCID authenticated="true">https://orcid.org/0000-0002-5512-0443</ORCID>
         </person_name>
       </contributors>
       <titles>

Deposition 1:
        <doi>10.15252/rc.2025299272</doi>
        <doi>10.15252/rc.2025081109</doi>
        <doi>10.15252/rc.2025526950</doi>
        <doi>10.15252/rc.2025235721</doi>
---

+++

@@ -153,7 +153,7 @@

               <institution_department>Cell Architecture Laboratory</institution_department>
             </institution>
           </affiliations>
-          <ORCID authenticated="true">https://orcid.org/http://orcid.org/0000-0003-4227-4811</ORCID>
+          <ORCID authenticated="true">https://orcid.org/0000-0003-4227-4811</ORCID>
         </person_name>
         <person_name sequence="additional" contributor_role="author">
           <given_name>Tatsuya</given_name>

In [ ]:
from mecadoi.crossref.api import deposit

responses = []
for deposition in corrected_depositions:
    response = deposit(deposition, verbose=1)
    responses.append(response)

POST https://doi.crossref.org/servlet/deposit
Content-Length: 8143
Content-Type: multipart/form-data; boundary=133b87bdca84955c8de281bc8f878b1e
--133b87bdca84955c8de281bc8f878b1e
Content-Disposition: form-data; name="login_id"

***
--133b87bdca84955c8de281bc8f878b1e
Content-Disposition: form-data; name="login_passwd"

***
--133b87bdca84955c8de281bc8f878b1e
Content-Disposition: form-data; name="fname"; filename="deposition.xml"

<doi_batch xmlns="http://www.crossref.org/schema/5.3.1" xmlns:rel="http://www.crossref.org/relations.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="5.3.1" xsi:schemaLocation="http://www.crossref.org/schema/5.3.1 http://www.crossref.org/schemas/crossref5.3.1.xsd">
  <head>
    <doi_batch_id>rc.1740363809815865604</doi_batch_id>
    <timestamp>1740363809815865604</timestamp>
    <depositor>
      <depositor_name>EMBO</depositor_name>
      <email_address>eidens@embl.de</email_address>
    </depositor>
    <registrant>EMBO</registrant>
  </head>
  <body>
    <peer_review language="en" revision-round="0" type="referee-report" stage="pre-publication">
      <contributors>
        <anonymous sequence="first" contributor_role="author"/>
      </contributors>
      <titles>
        <title>Peer Review #1 of Expression quantitative trait locus mapping in recombinant gametes using single nucleus RNA sequencing</title>
      </titles>
      <review_date>
        <month>1</month>
        <day>2</day>
        <year>2025</year>
      </review_date>
      <institution>
        <institution_name>Review Commons</institution_name>
      </institution>
      <running_number>1</running_number>
      <rel:program>
        <rel:related_item>
          <rel:inter_work_relation relationship-type="isReviewOf" identifier-type="doi">10.1101/2024.08.02.606310</rel:inter_work_relation>
        </rel:related_item>
      </rel:program>
      <doi_data>
        <doi>10.15252/rc.2025414611</doi>
        <resource>https://eeb.embo.org/doi/10.1101/2024.08.02.606310#rev0-rr1</resource>
      </doi_data>
    </peer_review>
    <peer_review language="en" revision-round="0" type="referee-report" stage="pre-publication">
      <contributors>
        <anonymous sequence="first" contributor_role="author"/>
      </contributors>
      <titles>
        <title>Peer Review #2 of Expression quantitative trait locus mapping in recombinant gametes using single nucleus RNA sequencing</title>
      </titles>
      <review_date>
        <month>1</month>
        <day>2</day>
        <year>2025</year>
      </review_date>
      <institution>
        <institution_name>Review Commons</institution_name>
      </institution>
      <running_number>2</running_number>
      <rel:program>
        <rel:related_item>
          <rel:inter_work_relation relationship-type="isReviewOf" identifier-type="doi">10.1101/2024.08.02.606310</rel:inter_work_relation>
        </rel:related_item>
      </rel:program>
      <doi_data>
        <doi>10.15252/rc.2025737807</doi>
        <resource>https://eeb.embo.org/doi/10.1101/2024.08.02.606310#rev0-rr2</resource>
      </doi_data>
    </peer_review>
    <peer_review language="en" revision-round="0" type="author-comment" stage="pre-publication">
      <contributors>
        <person_name sequence="first" contributor_role="author">
          <given_name>Matthew</given_name>
          <surname>Parker</surname>
          <affiliations>
            <institution>
              <institution_name>Max Planck Institute for Plant Breeding Research</institution_name>
              <institution_place>Germany</institution_place>
            </institution>
          </affiliations>
        </person_name>
        <person_name sequence="additional" contributor_role="author">
          <given_name>Samija</given_name>
          <surname>Amar</surname>
          <affiliations>
            <institution>
              <institution_name>Max Planck Institute for Plant Breeding Research</institution_name>
            </institution>
          </affiliations>
          <ORCID authenticated="true">https://orcid.org/0000-0001-7811-1614</ORCID>
        </person_name>
        <person_name sequence="additional" contributor_role="author">
          <given_name>José A</given_name>
          <surname>Campoy</surname>
          <affiliations>
            <institution>
              <institution_name>Max Planck Institute for Plant Breeding Research</institution_name>
            </institution>
          </affiliations>
          <ORCID authenticated="true">https://orcid.org/0000-0002-6018-5698</ORCID>
        </person_name>
        <person_name sequence="additional" contributor_role="author">
          <given_name>Kristin</given_name>
          <surname>Krause</surname>
          <affiliations>
            <institution>
              <institution_name>Max Planck Institute for Plant Breeding Research</institution_name>
            </institution>
          </affiliations>
        </person_name>
        <person_name sequence="additional" contributor_role="author">
          <given_name>Sergio</given_name>
          <surname>Tusso</surname>
          <affiliations>
            <institution>
              <institution_name>Ludwig-Maximilians-Universität München</institution_name>
            </institution>
          </affiliations>
          <ORCID authenticated="true">https://orcid.org/0000-0002-0612-9230</ORCID>
        </person_name>
        <person_name sequence="additional" contributor_role="author">
          <given_name>Magdalena</given_name>
          <surname>Marek</surname>
          <affiliations>
            <institution>
              <institution_name>Max Planck Genome Center</institution_name>
            </institution>
          </affiliations>
        </person_name>
        <person_name sequence="additional" contributor_role="author">
          <given_name>Bruno</given_name>
          <surname>Huettel</surname>
          <affiliations>
            <institution>
              <institution_name>Max-Planck Institute for Plant Breeding Research</institution_name>
              <institution_place>Cologne, Germany</institution_place>
              <institution_department>Max Planck Genome Centre</institution_department>
            </institution>
          </affiliations>
        </person_name>
        <person_name sequence="additional" contributor_role="author">
          <given_name>Korbinian</given_name>
          <surname>Schneeberger</surname>
          <affiliations>
            <institution>
              <institution_name>Ludwig Maximilian Universität München</institution_name>
              <institution_place>Munich, Germany</institution_place>
              <institution_department>Department of Genetics, Faculty of Biology</institution_department>
            </institution>
          </affiliations>
          <ORCID authenticated="true">https://orcid.org/0000-0002-5512-0443</ORCID>
        </person_name>
      </contributors>
      <titles>
        <title>Author Reply to Peer Reviews of Expression quantitative trait locus mapping in recombinant gametes using single nucleus RNA sequencing</title>
      </titles>
      <review_date>
        <month>1</month>
        <day>2</day>
        <year>2025</year>
      </review_date>
      <institution>
        <institution_name>Review Commons</institution_name>
      </institution>
      <running_number>Author Reply</running_number>
      <rel:program>
        <rel:related_item>
          <rel:inter_work_relation relationship-type="isReviewOf" identifier-type="doi">10.1101/2024.08.02.606310</rel:inter_work_relation>
        </rel:related_item>
        <rel:related_item>
          <rel:inter_work_relation relationship-type="isReplyTo" identifier-type="doi">10.15252/rc.2025414611</rel:inter_work_relation>
        </rel:related_item>
        <rel:related_item>
          <rel:inter_work_relation relationship-type="isReplyTo" identifier-type="doi">10.15252/rc.2025737807</rel:inter_work_relation>
        </rel:related_item>
      </rel:program>
      <doi_data>
        <doi>10.15252/rc.2025897098</doi>
        <resource>https://eeb.embo.org/doi/10.1101/2024.08.02.606310#rev0-ar</resource>
      </doi_data>
    </peer_review>
  </body>
</doi_batch>

--133b87bdca84955c8de281bc8f878b1e--

POST https://doi.crossref.org/servlet/deposit
Content-Length: 9365
Content-Type: multipart/form-data; boundary=487a9add236081eaac3e3c694ea78111
--487a9add236081eaac3e3c694ea78111
Content-Disposition: form-data; name="login_id"

***
--487a9add236081eaac3e3c694ea78111
Content-Disposition: form-data; name="login_passwd"

***
--487a9add236081eaac3e3c694ea78111
Content-Disposition: form-data; name="fname"; filename="deposition.xml"

<doi_batch xmlns="http://www.crossref.org/schema/5.3.1" xmlns:rel="http://www.crossref.org/relations.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="5.3.1" xsi:schemaLocation="http://www.crossref.org/schema/5.3.1 http://www.crossref.org/schemas/crossref5.3.1.xsd">
  <head>
    <doi_batch_id>rc.1763529781943232157</doi_batch_id>
    <timestamp>1763529781943232157</timestamp>
    <depositor>
      <depositor_name>EMBO</depositor_name>
      <email_address>eidens@embl.de</email_address>
    </depositor>
    <registrant>EMBO</registrant>
  </head>
  <body>
    <peer_review language="en" revision-round="0" type="referee-report" stage="pre-publication">
      <contributors>
        <anonymous sequence="first" contributor_role="author"/>
      </contributors>
      <titles>
        <title>Peer Review #1 of Condensin II collaborates with cohesin to establish and maintain interphase chromosome territories</title>
      </titles>
      <review_date>
        <month>11</month>
        <day>16</day>
        <year>2025</year>
      </review_date>
      <institution>
        <institution_name>Review Commons</institution_name>
      </institution>
      <running_number>1</running_number>
      <rel:program>
        <rel:related_item>
          <rel:inter_work_relation relationship-type="isReviewOf" identifier-type="doi">10.1101/2025.07.25.666893</rel:inter_work_relation>
        </rel:related_item>
      </rel:program>
      <doi_data>
        <doi>10.15252/rc.2025299272</doi>
        <resource>https://eeb.embo.org/doi/10.1101/2025.07.25.666893#rev0-rr1</resource>
      </doi_data>
    </peer_review>
    <peer_review language="en" revision-round="0" type="referee-report" stage="pre-publication">
      <contributors>
        <anonymous sequence="first" contributor_role="author"/>
      </contributors>
      <titles>
        <title>Peer Review #2 of Condensin II collaborates with cohesin to establish and maintain interphase chromosome territories</title>
      </titles>
      <review_date>
        <month>11</month>
        <day>16</day>
        <year>2025</year>
      </review_date>
      <institution>
        <institution_name>Review Commons</institution_name>
      </institution>
      <running_number>2</running_number>
      <rel:program>
        <rel:related_item>
          <rel:inter_work_relation relationship-type="isReviewOf" identifier-type="doi">10.1101/2025.07.25.666893</rel:inter_work_relation>
        </rel:related_item>
      </rel:program>
      <doi_data>
        <doi>10.15252/rc.2025081109</doi>
        <resource>https://eeb.embo.org/doi/10.1101/2025.07.25.666893#rev0-rr2</resource>
      </doi_data>
    </peer_review>
    <peer_review language="en" revision-round="0" type="referee-report" stage="pre-publication">
      <contributors>
        <anonymous sequence="first" contributor_role="author"/>
      </contributors>
      <titles>
        <title>Peer Review #3 of Condensin II collaborates with cohesin to establish and maintain interphase chromosome territories</title>
      </titles>
      <review_date>
        <month>11</month>
        <day>16</day>
        <year>2025</year>
      </review_date>
      <institution>
        <institution_name>Review Commons</institution_name>
      </institution>
      <running_number>3</running_number>
      <rel:program>
        <rel:related_item>
          <rel:inter_work_relation relationship-type="isReviewOf" identifier-type="doi">10.1101/2025.07.25.666893</rel:inter_work_relation>
        </rel:related_item>
      </rel:program>
      <doi_data>
        <doi>10.15252/rc.2025526950</doi>
        <resource>https://eeb.embo.org/doi/10.1101/2025.07.25.666893#rev0-rr3</resource>
      </doi_data>
    </peer_review>
    <peer_review language="en" revision-round="0" type="author-comment" stage="pre-publication">
      <contributors>
        <person_name sequence="first" contributor_role="author">
          <given_name>Takao</given_name>
          <surname>Ono</surname>
          <affiliations>
            <institution>
              <institution_name>RIKEN</institution_name>
              <institution_place>Wako, Japan [JP]</institution_place>
            </institution>
          </affiliations>
          <ORCID authenticated="true">https://orcid.org/0000-0002-0498-8293</ORCID>
        </person_name>
        <person_name sequence="additional" contributor_role="author">
          <given_name>Masatoshi</given_name>
          <surname>Takagi</surname>
          <affiliations>
            <institution>
              <institution_name>RIKEN</institution_name>
              <institution_place>Wako, Japan [JP]</institution_place>
              <institution_department>Laboratory of Cellular Dynamics</institution_department>
            </institution>
          </affiliations>
        </person_name>
        <person_name sequence="additional" contributor_role="author">
          <given_name>Hideyuki</given_name>
          <surname>Tanabe</surname>
          <affiliations>
            <institution>
              <institution_name>The Graduate University for Advanced Studies</institution_name>
              <institution_place>Hayama, Japan [JP]</institution_place>
              <institution_department>School of Advanced Sciences</institution_department>
            </institution>
          </affiliations>
        </person_name>
        <person_name sequence="additional" contributor_role="author">
          <given_name>Tomoko</given_name>
          <surname>Saito-Fujita</surname>
          <affiliations>
            <institution>
              <institution_name>The Cancer Institute of JFCR</institution_name>
              <institution_place>Japan [JP]</institution_place>
            </institution>
          </affiliations>
        </person_name>
        <person_name sequence="additional" contributor_role="author">
          <given_name>Noriko</given_name>
          <surname>Saitoh</surname>
          <affiliations>
            <institution>
              <institution_name>The Cancer Institute of Japanese Foundation for Cancer Research</institution_name>
              <institution_place>Ariake, Japan [JP]</institution_place>
              <institution_department>Division of Cancer Biology</institution_department>
            </institution>
          </affiliations>
        </person_name>
        <person_name sequence="additional" contributor_role="author">
          <given_name>Akatsuki</given_name>
          <surname>Kimura</surname>
          <affiliations>
            <institution>
              <institution_name>National Institute of Genetics</institution_name>
              <institution_place>Mishima, Japan [JP]</institution_place>
              <institution_department>Cell Architecture Laboratory</institution_department>
            </institution>
          </affiliations>
          <ORCID authenticated="true">https://orcid.org/0000-0003-4227-4811</ORCID>
        </person_name>
        <person_name sequence="additional" contributor_role="author">
          <given_name>Tatsuya</given_name>
          <surname>Hirano</surname>
          <affiliations>
            <institution>
              <institution_name>RIKEN</institution_name>
              <institution_place>Wako, Japan [JP]</institution_place>
              <institution_department>Chromosome Dynamics Laboratory</institution_department>
            </institution>
          </affiliations>
          <ORCID authenticated="true">https://orcid.org/0000-0002-4219-6473</ORCID>
        </person_name>
      </contributors>
      <titles>
        <title>Author Reply to Peer Reviews of Condensin II collaborates with cohesin to establish and maintain interphase chromosome territories</title>
      </titles>
      <review_date>
        <month>11</month>
        <day>16</day>
        <year>2025</year>
      </review_date>
      <institution>
        <institution_name>Review Commons</institution_name>
      </institution>
      <running_number>Author Reply</running_number>
      <rel:program>
        <rel:related_item>
          <rel:inter_work_relation relationship-type="isReviewOf" identifier-type="doi">10.1101/2025.07.25.666893</rel:inter_work_relation>
        </rel:related_item>
        <rel:related_item>
          <rel:inter_work_relation relationship-type="isReplyTo" identifier-type="doi">10.15252/rc.2025299272</rel:inter_work_relation>
        </rel:related_item>
        <rel:related_item>
          <rel:inter_work_relation relationship-type="isReplyTo" identifier-type="doi">10.15252/rc.2025081109</rel:inter_work_relation>
        </rel:related_item>
        <rel:related_item>
          <rel:inter_work_relation relationship-type="isReplyTo" identifier-type="doi">10.15252/rc.2025526950</rel:inter_work_relation>
        </rel:related_item>
      </rel:program>
      <doi_data>
        <doi>10.15252/rc.2025235721</doi>
        <resource>https://eeb.embo.org/doi/10.1101/2025.07.25.666893#rev0-ar</resource>
      </doi_data>
    </peer_review>
  </body>
</doi_batch>

--487a9add236081eaac3e3c694ea78111--

In [ ]:
responses

['\n\n\n\n<html>\n<head><title>SUCCESS</title>\n</head>\n<body>\n<h2>SUCCESS</h2>\n<p>Your batch submission was successfully received.</p>\n</body>\n</html>\n',
 '\n\n\n\n<html>\n<head><title>SUCCESS</title>\n</head>\n<body>\n<h2>SUCCESS</h2>\n<p>Your batch submission was successfully received.</p>\n</body>\n</html>\n']

In [ ]:
# write deposition attempt fixes back to the database?