How many Review-Commons-reviewed preprints have reviews/author replies without DOIs?

In [1]:
import requests
import pandas

In [2]:
dois_by_reviewing_service = requests.get("https://eeb.embo.org/api/v1/by_reviewing_service/").json()
revcom_data = [
    s
    for s in dois_by_reviewing_service
    if s["id"] == "review commons"
][0]
revcom_data

{'id': 'review commons',
 'papers': [{'rank': '',
   'pub_date': '2025-04-25T00:00:00Z',
   'slug': 'Sex-lethal-is-recruited-to-chromatin-to-promote-neuronal-tRNA-synthesis-in-males-through-RNA-Polymerase-III-regulation',
   'doi': '10.1101/2025.04.25.650657'},
  {'rank': '',
   'pub_date': '2020-01-11T00:00:00Z',
   'slug': 'Integrative-analysis-of-large-scale-loss-of-function-screens-identifies-robust-cancer-associated-genetic-interactions',
   'doi': '10.1101/646810'},
  {'rank': '',
   'pub_date': '2020-05-07T00:00:00Z',
   'slug': 'Transcriptional-comparison-of-Testicular-Adrenal-Rest-Tumors-with-fetal-and-adult-tissues',
   'doi': '10.1101/2020.05.07.082313'},
  {'rank': '',
   'pub_date': '2020-04-23T00:00:00Z',
   'slug': 'ESI-mutagenesis-A-one-step-method-for-introducing-point-mutations-into-bacterial-artificial-chromosome-transgenes',
   'doi': '10.1101/844282'},
  {'rank': '',
   'pub_date': '2020-05-22T00:00:00Z',
   'slug': 'A-large-accessory-protein-interactome-is-rewired-across-environments',
   'doi': '10.1101/2020.05.20.106583'},
  {'rank': '',
   'pub_date': '2020-01-11T00:00:00Z',
   'slug': 'Genome-wide-transcriptomics-identifies-an-early-preclinical-signature-of-prion-infection',
   'doi': '10.1101/2020.01.10.901637'},
  {'rank': '',
   'pub_date': '2020-02-27T00:00:00Z',
   'slug': 'Low-protein-high-carbohydrate-diet-induces-AMPK-dependent-canonical-and-non-canonical-thermogenic-response-in-subcutaneous-adipose-tissue',
   'doi': '10.1101/2020.02.26.966002'},
  {'rank': '',
   'pub_date': '2020-02-12T00:00:00Z',
   'slug': 'Transcytosis-via-the-late-endocytic-pathway-as-a-cell-morphogenetic-mechanism',
   'doi': '10.1101/2020.01.16.909200'},
  {'rank': '',
   'pub_date': '2021-04-29T00:00:00Z',
   'slug': 'Marburg-and-Ebola-virus-infections-elicit-a-complex-muted-inflammatory-state-in-bats',
   'doi': '10.1101/2020.04.13.039503'},
  {'rank': '',
   'pub_date': '2020-03-27T00:00:00Z',
   'slug': 'Single-cell-transcriptome-analysis-reveals-cell-cell-communication-and-thyrocyte-diversity-in-the-zebrafish-thyroid-gland',
   'doi': '10.1101/2020.01.13.891630'},
  {'rank': '',
   'pub_date': '2019-12-24T00:00:00Z',
   'slug': 'The-interaction-between-non-fusogenic-Sec22b-Stx-complexes-and-Extended-Synaptotagmins-promotes-neurite-growth-and-ramification',
   'doi': '10.1101/2019.12.24.886648'},
  {'rank': '',
   'pub_date': '2021-01-04T00:00:00Z',
   'slug': 'Unconventional-kinetochore-kinases-KKT2-and-KKT3-have-unique-centromere-localization-domains',
   'doi': '10.1101/2019.12.13.875419'},
  {'rank': '',
   'pub_date': '2020-04-13T00:00:00Z',
   'slug': 'Cytosolic-Adaptation-to-Mitochondrial-Precursor-Overaccumulation-Stress-Induces-Progressive-Muscle-Wasting',
   'doi': '10.1101/733097'},
  {'rank': '',
   'pub_date': '2020-05-03T00:00:00Z',
   'slug': 'Homology-directed-repair-involves-multiple-strand-invasion-cycles-in-fission-yeast',
   'doi': '10.1101/2020.05.03.074468'},
  {'rank': '',
   'pub_date': '2020-11-23T00:00:00Z',
   'slug': 'Limiting-DNA-polymerase-delta-alters-replication-dynamics-and-leads-to-a-dependence-on-checkpoint-activation-and-recombination-mediated-DNA-repair',
   'doi': '10.1101/2019.12.17.879544'},
  {'rank': '',
   'pub_date': '2020-07-15T00:00:00Z',
   'slug': 'The-lupus-autoantigen-La-is-an-Xist-binding-protein-involved-in-Xist-folding-and-cloud-formation',
   'doi': '10.1101/2020.03.07.981860'},
  {'rank': '',
   'pub_date': '2020-05-08T00:00:00Z',
   'slug': 'Stable-kinetochore-microtubule-attachments-restrict-MTOC-position-and-spindle-elongation-in-acentrosomal-oocytes',
   'doi': '10.1101/2020.05.07.081786'},
  {'rank': '',
   'pub_date': '2020-07-17T00:00:00Z',
   'slug': 'Novel-features-of-centriole-polarity-and-cartwheel-stacking-revealed-by-cryo-tomography',
   'doi': '10.1101/2020.07.17.208082'},
  {'rank': '',
   'pub_date': '2020-06-23T00:00:00Z',
   'slug': 'Structures-of-three-MORN-repeat-proteins-and-a-re-evaluation-of-the-proposed-lipid-binding-properties-of-MORN-repeats',
   'doi': '10.1101/826180'},
  {'rank': '',
   'pub_date': '2020-05-28T00:00:00Z',
   'slug': 'C-elegans-establishes-germline-versus-soma-by-balancing-inherited-histone-methylation',
   'doi': '10.1101/2020.01.22.914580'},
  {'rank': '',
   'pub_date': '2019-05-13T00:00:00Z',
   'slug': 'The-Glycolytic-Protein-Phosphofructokinase-Dynamically-Relocalizes-into-Subcellular-Compartments-with-Liquid-like-Properties-i-in-vivo-i-',
   'doi': '10.1101/636449'},
  {'rank': '',
   'pub_date': '2020-02-25T00:00:00Z',
   'slug': 'RNF40-dependent-epigenetic-regulation-of-actin-cytoskeletal-dynamics-is-required-for-HER2-driven-mammary-tumorigenesis',
   'doi': '10.1101/2020.02.24.962902'},
  {'rank': '',
   'pub_date': '2020-07-13T00:00:00Z',
   'slug': 'Optogenetic-control-of-PRC1-reveals-that-bridging-fibers-promote-chromosome-alignment-by-overlap-length-dependent-forces',
   'doi': '10.1101/865394'},
  {'rank': '',
   'pub_date': '2020-07-01T00:00:00Z',
   'slug': 'High-content-Imaging-based-Pooled-CRISPR-Screens-in-Mammalian-Cells',
   'doi': '10.1101/2020.06.30.179648'},
  {'rank': '',
   'pub_date': '2020-02-05T00:00:00Z',
   'slug': 'Protective-anti-prion-antibodies-in-human-immunoglobulin-repertoires',
   'doi': '10.1101/2020.02.05.933721'},
  {'rank': '',
   'pub_date': '2020-01-13T00:00:00Z',
   'slug': 'Natural-copy-number-differences-of-tandemly-repeated-small-nucleolar-RNAs-in-the-Prader-Willi-syndrome-genomic-region-regulate-individual-behavioral-responses-in-mammals',
   'doi': '10.1101/476010'},
  {'rank': '',
   'pub_date': '2019-12-19T00:00:00Z',
   'slug': 'Cell-cycle-dynamics-of-lamina-associated-DNA',
   'doi': '10.1101/2019.12.19.881979'},
  {'rank': '',
   'pub_date': '2020-01-11T00:00:00Z',
   'slug': 'Novel-IRE1-dependent-proinflammatory-signaling-controls-tumor-infiltration-by-myeloid-cells',
   'doi': '10.1101/533018'},
  {'rank': '',
   'pub_date': '2020-06-30T00:00:00Z',
   'slug': 'Heh2-Man1-may-be-an-evolutionarily-conserved-sensor-of-NPC-assembly-state',
   'doi': '10.1101/2020.06.29.178129'},
  {'rank': '',
   'pub_date': '2019-12-17T00:00:00Z',
   'slug': 'Bacterial-killing-by-complement-requires-direct-anchoring-of-Membrane-Attack-Complex-precursor-C5b-7',
   'doi': '10.1101/2019.12.17.877639'},
  {'rank': '',
   'pub_date': '2020-03-02T00:00:00Z',
   'slug': 'Profiles-of-circulating-histidine-rich-glycoprotein-associate-with-chronological-age-and-risk-of-all-cause-mortality',
   'doi': '10.1101/464909'},
  {'rank': '',
   'pub_date': '2019-10-13T00:00:00Z',
   'slug': 'A-fully-automated-deep-learning-pipeline-for-high-throughput-colony-segmentation-and-classification',
   'doi': '10.1101/801845'},
  {'rank': '',
   'pub_date': '2020-02-13T00:00:00Z',
   'slug': 'Second-messenger-control-of-mRNA-translation-by-dynamic-ribosome-modification',
   'doi': '10.1101/2020.02.13.947879'},
  {'rank': '',
   'pub_date': '2020-06-03T00:00:00Z',
   'slug': 'Implications-for-tetraspanin-enriched-microdomain-assembly-based-on-structures-of-CD9-with-EWI-F',
   'doi': '10.1101/2020.06.02.130047'},
  {'rank': '',
   'pub_date': '2019-12-20T00:00:00Z',
   'slug': 'Rewired-signaling-network-in-T-cells-expressing-the-chimeric-antigen-receptor-CAR-',
   'doi': '10.1101/2019.12.19.883496'},
  {'rank': '',
   'pub_date': '2020-04-17T00:00:00Z',
   'slug': 'The-activity-of-human-enhancers-is-modulated-by-the-splicing-of-their-associated-lncRNAs',
   'doi': '10.1101/2020.04.17.045971'},
  {'rank': '',
   'pub_date': '2020-03-05T00:00:00Z',
   'slug': 'Cell-to-cell-and-genome-to-genome-variability-of-Adenovirus-transcription-tuned-by-the-cell-cycle',
   'doi': '10.1101/2020.02.27.967471'},
  {'rank': '',
   'pub_date': '2020-01-21T00:00:00Z',
   'slug': 'KAT2-mediated-acetylation-switches-the-mode-of-PALB2-chromatin-association-to-safeguard-genome-integrity',
   'doi': '10.1101/735811'},
  {'rank': '',
   'pub_date': '2020-04-14T00:00:00Z',
   'slug': 'Alpha-satellite-RNA-transcripts-are-repressed-by-centromere-nucleolus-associations',
   'doi': '10.1101/2020.04.14.040766'},
  {'rank': '',
   'pub_date': '2020-06-16T00:00:00Z',
   'slug': 'Mapping-the-Algal-Secret-Genome-The-small-RNA-Locus-Map-for-Chlamydomonas-reinhardtii',
   'doi': '10.1101/2020.06.16.149575'},
  {'rank': '',
   'pub_date': '2020-05-05T00:00:00Z',
   'slug': 'Retrocopying-expands-the-functional-repertoire-of-APOBEC3-antiviral-proteins-in-primates',
   'doi': '10.1101/2020.02.12.944629'},
  {'rank': '',
   'pub_date': '2020-09-02T00:00:00Z',
   'slug': 'A-stress-induced-Tyrosine-tRNA-depletion-response-mediates-codon-based-translational-repression-and-growth-suppression',
   'doi': '10.1101/416727'},
  {'rank': '',
   'pub_date': '2020-05-10T00:00:00Z',
   'slug': 'Coordinated-crosstalk-between-microtubules-and-actin-by-a-spectraplakin-regulates-lumen-formation-and-branching',
   'doi': '10.1101/2020.05.09.085753'},
  {'rank': '',
   'pub_date': '2020-02-11T00:00:00Z',
   'slug': 'The-inhibition-of-LSD1-via-sequestration-contributes-to-tau-mediated-neurodegeneration',
   'doi': '10.1101/745133'},
  {'rank': '',
   'pub_date': '2020-04-23T00:00:00Z',
   'slug': 'Vasohibin-1-mediated-tubulin-detyrosination-selectively-regulates-secondary-sprouting-and-lymphangiogenesis-in-the-zebrafish-trunk',
   'doi': '10.1101/2020.04.23.053256'},
  {'rank': '',
   'pub_date': '2020-07-21T00:00:00Z',
   'slug': 'Increased-processing-of-SINE-B2-non-coding-RNAs-unveils-a-novel-type-of-transcriptome-de-regulation-underlying-amyloid-beta-neuro-pathology',
   'doi': '10.1101/2020.07.20.212886'},
  {'rank': '',
   'pub_date': '2019-11-26T00:00:00Z',
   'slug': 'Kinetochore-phosphatases-suppress-autonomous-kinase-activity-to-control-the-spindle-assembly-checkpoint',
   'doi': '10.1101/856773'},
  {'rank': '',
   'pub_date': '2020-02-21T00:00:00Z',
   'slug': 'An-asymmetry-in-the-frequency-and-position-of-mitosis-in-the-epiblast-precedes-gastrulation-and-suggests-a-role-for-mitotic-rounding-in-cell-delamination-during-primitive-streak-epithelial-mesenchymal-transition',
   'doi': '10.1101/2020.02.21.959080'},
  {'rank': '',
   'pub_date': '2020-07-21T00:00:00Z',
   'slug': 'Unveiling-the-dimer-monomer-propensities-of-Smad-MH1-DNA-complexes',
   'doi': '10.1101/833319'},
  {'rank': '',
   'pub_date': '2020-02-23T00:00:00Z',
   'slug': 'Mitofusin-2-regulates-neutrophil-adhesive-migration-and-the-actin-cytoskeleton',
   'doi': '10.1101/608091'},
  {'rank': '',
   'pub_date': '2021-08-19T00:00:00Z',
   'slug': 'Python-Microscope-A-new-open-source-Python-library-for-the-control-of-microscopes',
   'doi': '10.1101/2021.01.18.427171'},
  {'rank': '',
   'pub_date': '2020-07-03T00:00:00Z',
   'slug': 'Spatial-Variation-of-Microtubule-Depolymerization-in-Large-Asters-Suggests-Regulation-by-MAP-Depletion',
   'doi': '10.1101/2020.06.26.172783'},
  {'rank': '',
   'pub_date': '2020-10-23T00:00:00Z',
   'slug': 'Trehalose-and-α-glucan-mediate-distinct-abiotic-stress-responses-in-Pseudomonas-aeruginosa',
   'doi': '10.1101/2020.10.23.351924'},
  {'rank': '',
   'pub_date': '2020-06-06T00:00:00Z',
   'slug': 'Fitness-landscape-of-a-dynamic-RNA-structure',
   'doi': '10.1101/2020.06.06.130575'},
  {'rank': '',
   'pub_date': '2021-01-19T00:00:00Z',
   'slug': 'Fluorescence-based-3D-targeting-of-FIB-SEM-acquisition-of-small-volumes-in-large-samples',
   'doi': '10.1101/2021.01.18.427072'},
  {'rank': '',
   'pub_date': '2021-04-12T00:00:00Z',
   'slug': 'Activation-of-innate-immune-signalling-during-development-predisposes-to-inflammatory-intestine-and-shortened-lifespan',
   'doi': '10.1101/2021.04.12.439419'},
  {'rank': '',
   'pub_date': '2020-07-06T00:00:00Z',
   'slug': 'Metabolomics-and-lipidomics-in-C-elegans-using-a-single-sample-preparation',
   'doi': '10.1101/2020.07.06.190017'},
  {'rank': '',
   'pub_date': '2021-04-06T00:00:00Z',
   'slug': 'Monitoring-single-cell-dynamics-of-entry-into-quiescence-during-an-unperturbed-lifecycle',
   'doi': '10.1101/2020.11.25.395608'},
  {'rank': '',
   'pub_date': '2021-03-20T00:00:00Z',
   'slug': 'Total-parasite-biomass-but-not-peripheral-parasitaemia-is-associated-with-endothelial-and-haematological-perturbations-in-i-Plasmodium-vivax-i-patients',
   'doi': '10.1101/2021.03.19.21253933'},
  {'rank': '',
   'pub_date': '2021-02-04T00:00:00Z',
   'slug': 'CDK4-6-inhibitors-induce-replication-stress-to-cause-long-term-cell-cycle-withdrawal',
   'doi': '10.1101/2021.02.03.428245'},
  {'rank': '',
   'pub_date': '2021-04-10T00:00:00Z',
   'slug': 'The-structure-and-flexibility-analysis-of-the-Arabidopsis-Synaptotagmin-1-reveal-the-basis-of-its-regulation-at-membrane-contact-sites',
   'doi': '10.1101/2021.04.09.438084'},
  {'rank': '',
   'pub_date': '2021-03-11T00:00:00Z',
   'slug': 'Co-chaperone-involvement-in-knob-biogenesis-implicates-host-derived-chaperones-in-malaria-virulence',
   'doi': '10.1101/2021.03.11.434953'},
  {'rank': '',
   'pub_date': '2021-02-03T00:00:00Z',
   'slug': 'Paradoxical-neuronal-hyperexcitability-in-a-mouse-model-of-mitochondrial-pyruvate-import-deficiency',
   'doi': '10.1101/2020.12.22.423903'},
  {'rank': '',
   'pub_date': '2020-10-14T00:00:00Z',
   'slug': 'High-dimensional-immunotyping-of-the-obese-tumor-microenvironment-reveals-model-specific-adaptation',
   'doi': '10.1101/2020.10.14.338806'},
  {'rank': '',
   'pub_date': '2021-01-06T00:00:00Z',
   'slug': 'Glucocorticoid-receptor-activation-induces-gene-specific-transcriptional-memory-and-universally-reversible-changes-in-chromatin-accessibility',
   'doi': '10.1101/2021.01.05.425406'},
  {'rank': '',
   'pub_date': '2020-07-16T00:00:00Z',
   'slug': 'A-sensitive-and-affordable-multiplex-RT-qPCR-assay-for-SARS-CoV-2-detection',
   'doi': '10.1101/2020.07.14.20154005'},
  {'rank': '',
   'pub_date': '2020-07-10T00:00:00Z',
   'slug': 'Predicting-cell-health-phenotypes-using-image-based-morphology-profiling',
   'doi': '10.1101/2020.07.08.193938'},
  {'rank': '',
   'pub_date': '2020-02-10T00:00:00Z',
   'slug': 'Septins-coordinate-cell-wall-integrity-and-lipid-metabolism-in-a-sphingolipid-dependent-process',
   'doi': '10.1101/2020.02.09.940718'},
  {'rank': '',
   'pub_date': '2020-10-08T00:00:00Z',
   'slug': 'RIOK2-phosphorylation-by-RSK-promotes-synthesis-of-the-human-small-ribosomal-subunit',
   'doi': '10.1101/2020.10.07.329334'},
  {'rank': '',
   'pub_date': '2021-05-07T00:00:00Z',
   'slug': 'LAG3-is-not-expressed-in-human-and-murine-neurons-and-does-not-modulate-α-synucleinopathies',
   'doi': '10.1101/2021.04.25.441302'},
  {'rank': '',
   'pub_date': '2021-07-01T00:00:00Z',
   'slug': 'Oligodendrocytes-depend-on-MCL-1-to-prevent-spontaneous-apoptosis-and-white-matter-degeneration',
   'doi': '10.1101/2020.12.02.408138'},
  {'rank': '',
   'pub_date': '2020-11-27T00:00:00Z',
   'slug': 'Automated-Morphometric-Analysis-Reveals-Plasticity-Induced-by-Chronic-Antidepressant-Treatment-in-Hippocampal-Astrocytes',
   'doi': '10.1101/2020.11.26.399964'},
  {'rank': '',
   'pub_date': '2020-07-13T00:00:00Z',
   'slug': 'Conservation-of-the-Toxoplasma-conoid-complex-proteome-reveals-a-cryptic-conoid-in-Plasmodium-that-differentiates-between-blood-and-vector-stage-zoites',
   'doi': '10.1101/2020.06.26.174284'},
  {'rank': '',
   'pub_date': '2020-12-01T00:00:00Z',
   'slug': 'Mechanical-competition-alters-the-cellular-interpretation-of-an-endogenous-genetic-programme',
   'doi': '10.1101/2020.10.15.333963'},
  {'rank': '',
   'pub_date': '2021-03-18T00:00:00Z',
   'slug': 'Tight-nanoscale-clustering-of-Fcγ-receptors-using-DNA-origami-promotes-phagocytosis',
   'doi': '10.1101/2021.03.18.436011'},
  {'rank': '',
   'pub_date': '2020-12-21T00:00:00Z',
   'slug': 'Stepwise-transmigration-cascade-of-T-and-B-cells-through-the-perivascular-channel-in-lymph-node-high-endothelial-venules',
   'doi': '10.1101/2020.12.20.423079'},
  {'rank': '',
   'pub_date': '2020-02-12T00:00:00Z',
   'slug': 'Single-mosquito-metatranscriptomics-identifies-vectors-emerging-pathogens-and-reservoirs-in-one-assay',
   'doi': '10.1101/2020.02.10.942854'},
  {'rank': '',
   'pub_date': '2021-04-06T00:00:00Z',
   'slug': 'Hda1C-restricts-the-transcription-initiation-frequency-to-limit-divergent-non-coding-RNA-transcription',
   'doi': '10.1101/2021.04.06.438606'},
  {'rank': '',
   'pub_date': '2020-11-27T00:00:00Z',
   'slug': 'Spurious-regulatory-connections-dictate-the-expression-fitness-landscape-of-translation-termination-factors',
   'doi': '10.1101/2020.11.27.400200'},
  {'rank': '',
   'pub_date': '2021-02-01T00:00:00Z',
   'slug': 'The-Drosophila-Baramicin-polypeptide-gene-protects-against-fungal-infection',
   'doi': '10.1101/2020.11.23.394148'},
  {'rank': '',
   'pub_date': '2020-01-29T00:00:00Z',
   'slug': 'Somatic-drift-and-rapid-loss-of-heterozygosity-suggest-small-effective-population-size-of-stem-cells-and-high-somatic-mutation-rate-in-asexual-planaria',
   'doi': '10.1101/665166'},
  {'rank': '',
   'pub_date': '2020-09-23T00:00:00Z',
   'slug': 'Glial-Hedgehog-and-lipid-metabolism-regulate-neural-stem-cell-proliferation-in-Drosophila',
   'doi': '10.1101/2020.05.18.100990'},
  {'rank': '',
   'pub_date': '2021-02-13T00:00:00Z',
   'slug': 'An-exon-junction-complex-independent-function-of-Barentsz-in-neuromuscular-synapse-growth',
   'doi': '10.1101/2021.02.13.430688'},
  {'rank': '',
   'pub_date': '2020-08-27T00:00:00Z',
   'slug': 'A-drug-repurposing-screen-identifies-hepatitis-C-antivirals-as-inhibitors-of-the-SARS-CoV-2-main-protease',
   'doi': '10.1101/2020.07.10.197889'},
  {'rank': '',
   'pub_date': '2021-03-22T00:00:00Z',
   'slug': 'Rabaptin5-targets-autophagy-to-damaged-endosomes-and-SCVs-by-interaction-with-FIP200-and-ATG16L1',
   'doi': '10.1101/2020.09.01.277764'},
  {'rank': '',
   'pub_date': '2020-09-14T00:00:00Z',
   'slug': 'Transcriptomic-entropy-benchmarks-stem-cell-derived-cardiomyocyte-maturation-against-endogenous-tissue-at-single-cell-level',
   'doi': '10.1101/2020.04.02.022632'},
  {'rank': '',
   'pub_date': '2020-09-14T00:00:00Z',
   'slug': 'On-the-evolution-of-chaperones-and-co-chaperones-and-the-expansion-of-proteomes-across-the-Tree-of-Life',
   'doi': '10.1101/2020.06.08.140319'},
  {'rank': '',
   'pub_date': '2020-04-07T00:00:00Z',
   'slug': 'Generating-functional-protein-variants-with-variational-autoencoders',
   'doi': '10.1101/2020.04.07.029264'},
  {'rank': '',
   'pub_date': '2021-04-21T00:00:00Z',
   'slug': 'A-novel-and-specific-regulator-of-neuronal-V-ATPase-in-Drosophila',
   'doi': '10.1101/2021.02.08.430253'},
  {'rank': '',
   'pub_date': '2020-05-15T00:00:00Z',
   'slug': 'CRYPTOCHROMES-confer-robustness-not-rhythmicity-to-circadian-timekeeping',
   'doi': '10.1101/2020.05.14.095968'},
  {'rank': '',
   'pub_date': '2021-02-05T00:00:00Z',
   'slug': 'The-Integrity-of-the-Speciation-Core-Complex-is-necessary-for-centromeric-binding-and-reproductive-isolation-in-Drosophila',
   'doi': '10.1101/2021.02.05.429932'},
  {'rank': '',
   'pub_date': '2020-08-27T00:00:00Z',
   'slug': 'The-circadian-oscillator-analysed-at-the-single-transcript-level',
   'doi': '10.1101/2020.08.26.268201'},
  {'rank': '',
   'pub_date': '2020-11-18T00:00:00Z',
   'slug': 'The-multi-scale-architecture-of-mammalian-sperm-flagella-and-implications-for-ciliary-motility',
   'doi': '10.1101/2020.11.18.388975'},
  {'rank': '',
   'pub_date': '2021-04-19T00:00:00Z',
   'slug': 'Shared-and-specific-functions-of-Arfs-1-5-at-the-Golgi-revealed-by-systematic-knockouts',
   'doi': '10.1101/2021.04.19.440443'},
  {'rank': '',
   'pub_date': '2020-09-20T00:00:00Z',
   'slug': 'Competition-for-MCM-Loading-at-Origins-Establishes-Replication-Timing-Patterns',
   'doi': '10.1101/2020.09.20.305276'},
  {'rank': '',
   'pub_date': '2020-07-22T00:00:00Z',
   'slug': 'On-the-Emergence-of-P-Loop-NTPase-and-Rossmann-Enzymes-from-a-Beta-Alpha-Beta-Ancestral-Fragment',
   'doi': '10.1101/2020.07.15.204123'},
  {'rank': '',
   'pub_date': '2020-11-18T00:00:00Z',

In [3]:
pandas.DataFrame([(p["doi"], p["pub_date"]) for p in revcom_data["papers"]], columns=["doi", "published_at"])

                            doi          published_at
0     10.1101/2025.04.25.650657  2025-04-25T00:00:00Z
1                10.1101/646810  2020-01-11T00:00:00Z
2     10.1101/2020.05.07.082313  2020-05-07T00:00:00Z
3                10.1101/844282  2020-04-23T00:00:00Z
4     10.1101/2020.05.20.106583  2020-05-22T00:00:00Z
...                         ...                   ...
1241  10.1101/2024.08.17.608283  2024-08-17T00:00:00Z
1242  10.1101/2024.01.06.574461  2024-01-08T00:00:00Z
1243  10.1101/2024.05.02.592277  2025-02-05T00:00:00Z
1244  10.1101/2024.08.19.608731  2024-08-20T00:00:00Z
1245  10.1101/2025.02.18.638827  2025-02-18T00:00:00Z

[1246 rows x 2 columns]

In [4]:
request_payload = {"dois": [p["doi"] for p in revcom_data["papers"]]}
data = requests.post("https://eeb.embo.org/api/v1/dois/", json=request_payload).json()
len(data), data[:3]

(1246,
 [{'id': 13735762,
   'doi': '10.1101/2024.12.09.627460',
   'version': '1.2',
   'source': 'f755ded0-6c89-1014-8d6f-a90e8b422d8b.meca',
   'journal': 'bioRxiv',
   'title': 'Deciphering the CD73⁺ Regulatory γδ T Cell ecosystem associated with poor survival in Ovarian cancer',
   'abstract': 'The ability of tumor cells to overcome immune surveillance is an essential step in tumor development and progression. Among the immune cells playing a role in tumor control, γδ T cells contribute to the immune response against many tumor types through their direct cytotoxic activity against cancer cells and their capacity to regulate the functions of other immune cells. However, their presence in the tumor microenvironment is also associated with poor prognosis, suggesting that γδ T cells may also have pro-tumor activities. We previously described a regulatory γδ T-cell subset that expresses CD73 and produces IL-10, IL-8 and adenosine. Here, we report a higher CD73+ γδ T cell density in the tumor microenvironment of ovarian cancer samples from patients with short-term than long-term survival. Starting from this original observation, we investigated their neighborhood and described a specific ecosystem according to their pro-tumor functions.',
   'journal_doi': None,
   'published_journal_title': None,
   'pub_date': '2025-07-21T00:00:00Z',
   'review_process': {'response': {'tags': ['PeerReviewed'],
     'link_incontext': 'https://hyp.is/Ljds3GI-EfC9EM8e9ifS9g/www.biorxiv.org/lookup/doi/10.1101/2024.12.09.627460',
     'related_article_uri': 'https://www.biorxiv.org/lookup/doi/10.1101/2024.12.09.627460',

In [5]:
reviews = [(a["doi"], r) for a in data for r in a["review_process"]["reviews"]]
responses = [(a["doi"], a["review_process"]["response"]) for a in data if a["review_process"]["response"] is not None]
len(reviews), len(responses)

(3597, 1241)

In [6]:
df = pandas.DataFrame(
    [
        (doi, r.get("doi", None), r["posting_date"])
        for doi, r in reviews + responses
    ],
    columns=["article_doi", "doi", "posting_date"]
)
df

,article_doi,doi,posting_date
0,10.1101/2024.12.09.627460,10.15252/rc.2025199660,2025-07-16T12:12:43.467979+00:00
1,10.1101/2024.12.09.627460,10.15252/rc.2025017913,2025-07-16T12:12:44.099831+00:00
2,10.1101/2024.12.09.627460,10.15252/rc.2025902375,2025-07-16T12:12:44.677135+00:00
3,10.1101/2024.01.20.573595,10.15252/rc.2024583495,2024-10-29T08:13:07.493621+00:00
4,10.1101/2024.01.20.573595,10.15252/rc.2024264773,2024-10-29T08:13:07.911046+00:00
...,...,...,...
4833,10.1101/2019.12.17.877639,10.15252/rc.2022106179,2020-03-09T17:17:30.246842+00:00
4834,10.1101/856773,10.15252/rc.2022058024,2020-02-05T11:16:05.099329+00:00
4835,10.1101/801845,10.15252/rc.2022491265,2020-03-27T10:22:42.778810+00:00
4836,10.1101/636449,10.15252/rc.2022543615,2020-04-20T10:17:34.902431+00:00
4837,10.1101/501833,10.15252/rc.2022103944,2022-10-10T11:14:31.556695+00:00

In [7]:
df[df["doi"].isna()]

                    article_doi   doi                      posting_date
72    10.1101/2025.05.13.653105  None  2025-08-07T08:12:54.959599+00:00
73    10.1101/2025.05.13.653105  None  2025-08-07T08:12:55.455253+00:00
74    10.1101/2025.05.13.653105  None  2025-08-07T08:12:55.767204+00:00
81    10.1101/2025.05.09.653054  None  2025-08-07T13:12:46.596786+00:00
82    10.1101/2025.05.09.653054  None  2025-08-07T13:12:47.082470+00:00
...                         ...   ...                               ...
4610  10.1101/2020.11.19.389544  None  2023-02-24T09:43:18.206218+00:00
4654  10.1101/2021.04.26.441408  None  2023-11-14T15:18:04.614783+00:00
4701  10.1101/2021.11.26.470092  None  2023-11-14T15:17:49.330376+00:00
4712  10.1101/2021.10.27.466115  None  2023-11-14T15:17:51.546792+00:00
4735  10.1101/2020.09.29.318857  None  2024-09-05T15:14:16.183230+00:00

[362 rows x 3 columns]

In [8]:
df[df["doi"].isna()]["article_doi"].value_counts()

10.1101/2023.05.29.542713    7
10.1101/2023.07.18.549574    5
10.1101/2023.12.25.573293    5
10.1101/2024.10.29.620637    5
10.1101/2022.10.17.512562    5
                            ..
10.1101/2022.07.15.500272    3
10.1101/2022.07.11.499563    3
10.1101/2025.05.09.653054    3
10.1101/2020.09.29.318857    3
10.1101/2023.07.07.548114    1
Name: article_doi, Length: 93, dtype: int64